### ISSUE TITLE
服务器部署，首页404 Not Found

### ISSUE THREAD

**Issue by 798714773** [maikeshequ/egg-nuxt-ssr#1]
在本地开发npm run dev 都正常
在本地npm start 首页刚开始是404 Not Found ，但过一会就正常了。

**在服务器npm start 首页404 Not Found** ， /test页面是正常的。

只修改了0.0.0.0为127.0.0.1，服务器nginx

很是苦恼，求助，下面是我的nginx配置

```
server {
    listen 443;
        server_name xxx.com; #填写绑定证书的域名
        ssl on;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; #按照这个协议配置
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;#按照这个套件配置
        ssl_prefer_server_ciphers on;

    location / {
        #设置主机头和客户端真实地址，以便服务器获取客户端真实 IP
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #禁用缓存
        proxy_buffering off;

        proxy_pass http://127.0.0.1:3000;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

}server {
    if ($host = xxx.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name xxx.com;
    return 404; # managed by Certbot
```

**Comment by maikeshequ** [comment]
非常感谢您对我们封装的组件的认可。同时为没能及时回复深感歉意。
推荐配置：
server {
&nbsp; &nbsp; listen 80;
&nbsp; &nbsp; server_name ***.com;
&nbsp; &nbsp; rewrite ^(.*)$ https://${server_name}$1 permanent;
}
server {
&nbsp; &nbsp; listen 443;
&nbsp; &nbsp; server_name ****.com;
&nbsp; &nbsp; charset utf-8;
&nbsp; &nbsp; client_max_body_size 75M;
&nbsp; &nbsp; ssl on;
&nbsp; &nbsp; ssl_certificate URL_TO_CRT.crt;
&nbsp; &nbsp; ssl_certificate_key URL_TOKEY.key;
&nbsp; &nbsp; ssl_session_timeout 5m;
&nbsp; &nbsp; ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
&nbsp; &nbsp; ssl_ciphers AESGCM:ALL:!DH:!EXPORT:!RC4:+HIGH:!MEDIUM:!LOW:!aNULL:!eNULL;
&nbsp; &nbsp; ssl_prefer_server_ciphers on;
&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; location / {
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Real-IP $remote_addr;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header Host $http_host;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_set_header X-NginX-Proxy true;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_pass http://127.0.0.1:3000;
&nbsp; &nbsp; &nbsp; &nbsp; proxy_redirect off;
&nbsp; &nbsp; }
}




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"798714773"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月21日(星期天) 晚上9:20
收件人:&nbsp;"maikeshequ/egg-nuxt-ssr"<egg-nuxt-ssr@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[maikeshequ/egg-nuxt-ssr] 服务器部署，首页404 Not Found (#1)





 
在本地开发npm run dev 都正常
 在本地npm start 首页刚开始是404 Not Found ，但过一会就正常了。
 
在服务器npm start 首页404 Not Found ， /test页面是正常的。
 
只修改了0.0.0.0为127.0.0.1，服务器nginx
 
很是苦恼，求助，下面是我的nginx配置
 server {     listen 443;         server_name xxx.com; #填写绑定证书的域名         ssl on;         ssl_session_timeout 5m;         ssl_protocols TLSv1 TLSv1.1 TLSv1.2; #按照这个协议配置         ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;#按照这个套件配置         ssl_prefer_server_ciphers on;     location / {         #设置主机头和客户端真实地址，以便服务器获取客户端真实 IP         proxy_set_header Host $host;         proxy_set_header X-Real-IP $remote_addr;         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;         #禁用缓存         proxy_buffering off;         proxy_pass http://127.0.0.1:3000;     }     #error_page  404              /404.html;     # redirect server error pages to the static page /50x.html     #     error_page   500 502 503 504  /50x.html;     location = /50x.html {         root   /usr/share/nginx/html;     } }server {     if ($host = xxx.com) {         return 301 https://$host$request_uri;     } # managed by Certbot     listen 80;     server_name xxx.com;     return 404; # managed by Certbot

**Comment by 798714773** [comment]
我尝试了您的这个nginx配置 还是不行 感觉不是nginx的问题了

1.感觉是nuxt没有build没有启动，首先 nuxt每次命令行里要有一个反馈询问才能往下执行，所以我**先把它关闭了** 参考这里https://github.com/nuxt/telemetry

2.app.js里面 this.app.env 命令行里提示好像要改成 this.app.config.env，下面这段配置没有看明白，感觉是这里的问题，在服务端我尝试打印this.app.config.env是local
```
config.dev = this.app.env !== 'production';
      const nuxt = new Nuxt(config);
      await nuxt.ready();
      // if (config.dev) {
        const builder = new Builder(nuxt);
        await builder.build();
      // }
```

3.我注释掉if 在服务器跑  还是有些问题，总觉得nuxt没有build。

在本地跑没有任何问题

**Comment by maikeshequ** [comment]
您好，非常抱歉这么久没有给您解决这个问题，我认真看了下您nginx配置文件，（由于nuxt是服务端渲染，故而前端页面不需要nginx做代理），直接使用 nginx做nodejs的反向代理就可以了。

**Comment by maikeshequ** [comment]
> 在本地开发npm run dev 都正常
> 在本地npm start 首页刚开始是404 Not Found ，但过一会就正常了。
> 
> **在服务器npm start 首页404 Not Found** ， /test页面是正常的。
> 
> 只修改了0.0.0.0为127.0.0.1，服务器nginx
> 
> 很是苦恼，求助，下面是我的nginx配置
> 
> ```
> server {
>     listen 443;
>         server_name xxx.com; #填写绑定证书的域名
>         ssl on;
>         ssl_session_timeout 5m;
>         ssl_protocols TLSv1 TLSv1.1 TLSv1.2; #按照这个协议配置
>         ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;#按照这个套件配置
>         ssl_prefer_server_ciphers on;
> 
>     location / {
>         #设置主机头和客户端真实地址，以便服务器获取客户端真实 IP
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         #禁用缓存
>         proxy_buffering off;
> 
>         proxy_pass http://127.0.0.1:3000;
>     }
> 
>     #error_page  404              /404.html;
> 
>     # redirect server error pages to the static page /50x.html
>     #
>     error_page   500 502 503 504  /50x.html;
>     location = /50x.html {
>         root   /usr/share/nginx/html;
>     }
> 
> }server {
>     if ($host = xxx.com) {
>         return 301 https://$host$request_uri;
>     } # managed by Certbot
> 
> 
>     listen 80;
>     server_name xxx.com;
>     return 404; # managed by Certbot
> ```
